import os

SECRET_MNEMONIC_DERIVATION_PEPPER = os.environ['SECRET_MNEMONIC_DERIVATION_PEPPER']
BASE_NODE_URL = os.environ['BASE_NODE_URL']
BASE_SIGNER_URL = os.environ['BASE_SIGNER_URL']
BASE_SIGNER_PUBLIC_KEY = os.environ['BASE_SIGNER_PUBLIC_KEY']
